# Generated by Django 4.2.5 on 2023-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lessonview',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lessonview',
            name='view_time',
        ),
        migrations.AddField(
            model_name='lessonview',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonview',
            name='watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonview',
            name='watched_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_seconds',
            field=models.PositiveIntegerField(),
        ),
    ]
